language: objective-c
osx_image: xcode11.6

branches:
  except:
    - localization
    - localization_1.1

env:
  global:
    - THEOS=theos

script:
- make package

before_install:
- brew install ldid fakeroot carthage
- git clone --single-branch -b master --recursive https://github.com/theos/theos.git $THEOS
- cd $TRAVIS_BUILD_DIR
- carthage update
