language: objective-c
osx_image: xcode11.6

branches:
  except:
    - localization
    - localization_1.1

env:
  global:
    - THEOS=theos

script:
- make package

before_install:
- carthage update --platform ios --verbose --new-resolver
- brew install ldid fakeroot
- git clone --depth=1 --recursive https://github.com/theos/theos.git $THEOS
