name: Build Zebra

on:
  push:
    branches:
      - master
      - carthage

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - uses: actions/cache@v1
      id: carthage-cache
      with:
        path: Carthage
        key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}

    - name: Build Dependencies
      if: steps.carthage-cache.outputs.cache-hit != 'true'
      run: |
        carthage bootstrap --no-use-binaries --platform iOS --cache-builds

    - name: Install Theos Dependencies
      run: brew install ldid fakeroot

    - name: Install Theos
      uses: actions/checkout@master
      with:
        repository: theos/theos
        path: theos
        ref: 8771215f765e774bfefdacc6ddf0e151c2973d49
        submodules: recursive

    - name: Build Package
      env:
        THEOS: theos
      run: make package
