name: Build Zebra

on:
  push:
    branches:
      - master
      - 1.2
      - carthage
  

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master

    - name: Install Dependencies
      run: brew install ldid fakeroot carthage

    - name: Build Dependencies
      run: carthage update --platform ios --new-resolver

    - name: Setup Theos
      uses: actions/checkout@master
      with:
        repository: theos/theos
        submodules: recursive

    - name: Build Package
      env:
        THEOS: theos
      run: make package
