name: Build Zebra

on:
  push:
    branches:
      - master
      - 1.1
  

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Dependencies
      env:
        THEOS: theos
      run: |
        brew install dpkg ldid fakeroot
        git clone --depth=1 --recursive --branch=next https://github.com/theos/theos.git $THEOS
        git submodule update --init --recursive
        
    - name: Build Package
      env:
        THEOS: theos
      run: make package
